name := "HW 11-122020"

version := "0.1"

scalaVersion := "2.13.4"

libraryDependencies += "org.scala-lang.modules" %% "scala-xml" % "1.3.0"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.9.2"
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.2.3"
libraryDependencies += "com.github.tototoshi" %% "scala-csv" % "1.3.6"
libraryDependencies += "com.lihaoyi" %% "upickle" % "0.9.5"
libraryDependencies += "com.lihaoyi" %% "os-lib" % "0.7.1"
libraryDependencies += "com.nrinaudo" %% "kantan.xpath" % "0.5.2"
libraryDependencies += "org.xerial" % "sqlite-jdbc" % "3.32.3.2"
libraryDependencies += "io.getquill" %% "quill-jdbc" % "3.6.0-RC3"
libraryDependencies += "com.typesafe.slick" %% "slick" % "3.3.3"
libraryDependencies += "com.typesafe.slick" %% "slick-codegen" % "3.3.3"
libraryDependencies += "net.debasishg" %% "redisclient" % "3.30"
libraryDependencies += "org.mongodb.scala" %% "mongo-scala-driver" % "4.0.5"
libraryDependencies += "com.outworkers" %% "phantom-dsl" % "2.59.0"
libraryDependencies += "org.neo4j.driver" % "neo4j-java-driver" % "4.1.1"
libraryDependencies += "com.dimafeng" %% "neotypes" % "0.15.1"